# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [129]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],
           [3,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [12]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [11]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [130]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a3)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [20]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2), dtype=None)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3, dtype=None)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10 ,size=(7,2), dtype=int)

array([[8, 9],
       [6, 6],
       [0, 9],
       [7, 5],
       [7, 6],
       [5, 2],
       [5, 3]])

In [35]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.90186338, 0.34523561, 0.73323881, 0.83760606, 0.08866518],
       [0.97875262, 0.49682265, 0.81085577, 0.13278538, 0.34308702],
       [0.05662472, 0.94506654, 0.44239773, 0.47021382, 0.86898163]])

In [43]:
# Set the random seed to 42
np.random.seed(seed=42)
np.random.randint(10, size=(4,6))
# Create a random array of numbers between 0 & 10 of size (4, 6)


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [131]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
number_array= np.random.randint(10, size=(3,7))
number_array

# Find the unique numbers in the array you just created
np.unique(number_array)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [46]:
# Find the 0'th index of the latest array you created
number_array[0]

array([8, 0, 9, 2, 6, 3, 8])

In [133]:
# Get the first 2 rows of latest array you created
b=number_array[:2]
b

array([[0, 8, 5, 2, 3, 3, 2],
       [9, 2, 2, 3, 6, 3, 8]])

In [134]:
# Get the first 2 values of the first 2 rows of the latest array
b[:2,:2]

array([[0, 8],
       [9, 2]])

In [68]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
c1=np.random.randint(10,size=(3,5))
c1
c2=np.ones((3,5))
c1

array([[9, 9, 2, 6, 0],
       [3, 3, 4, 6, 6],
       [3, 6, 2, 5, 1]])

In [136]:
# Add the two arrays together
ct=c1+c2

In [71]:
# Create another array of ones of shape (5, 3)
c3=np.ones((5,3))
c3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
# Try add the array of ones and the other most recent array together
c3+c1+c2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [73]:
# Create another array of ones of shape (3, 5)
c4=np.ones((3,5))

In [80]:
# Subtract the new array of ones from the other most recent array
c5=ct-c4
c5

array([[9., 9., 2., 6., 0.],
       [3., 3., 4., 6., 6.],
       [3., 6., 2., 5., 1.]])

In [81]:
# Multiply the ones array with the latest array
c6=c5*c4
c6

array([[9., 9., 2., 6., 0.],
       [3., 3., 4., 6., 6.],
       [3., 6., 2., 5., 1.]])

In [82]:
# Take the latest array to the power of 2 using '**'
c6**2

array([[81., 81.,  4., 36.,  0.],
       [ 9.,  9., 16., 36., 36.],
       [ 9., 36.,  4., 25.,  1.]])

In [83]:
# Do the same thing with np.square()
np.square(c6)

array([[81., 81.,  4., 36.,  0.],
       [ 9.,  9., 16., 36., 36.],
       [ 9., 36.,  4., 25.,  1.]])

In [84]:
# Find the mean of the latest array using np.mean()
np.mean(c6)

4.333333333333333

In [85]:
# Find the maximum of the latest array using np.max()
np.max(c6)

9.0

In [87]:
# Find the minimum of the latest array using np.min()
np.min(c6)

0.0

In [88]:
# Find the standard deviation of the latest array
np.std(c6)

2.5991451586157237

In [91]:
# Find the variance of the latest array
np.var(c6)

6.755555555555555

In [96]:
# Reshape the latest array to (3, 5, 1)
C7=np.reshape(c6,(3,5,1), order="C")
C7

array([[[9.],
        [9.],
        [2.],
        [6.],
        [0.]],

       [[3.],
        [3.],
        [4.],
        [6.],
        [6.]],

       [[3.],
        [6.],
        [2.],
        [5.],
        [1.]]])

In [97]:
# Transpose the latest array
C7.T

array([[[9., 3., 3.],
        [9., 3., 6.],
        [2., 4., 2.],
        [6., 6., 5.],
        [0., 6., 1.]]])

What does the transpose do?

In [101]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
c8=np.random.randint(10, size= (3,3))
c9=np.random.randint(10, size= (3,2))

In [102]:
# Perform a dot product on the two newest arrays you created
c8.dot(c9)

array([[ 16,  72],
       [ 84, 136],
       [ 48,  61]])

In [103]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
c10=np.random.randint(10, size= (4,3))
c11=np.random.randint(10, size= (4,3))

In [106]:
# Perform a dot product on the two newest arrays you created
c10.dot(c11)
#fixed after transposing the other array

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [107]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
c10.dot(c11.T)

array([[20, 49, 47, 62],
       [12, 56, 11, 60],
       [36,  0, 24, 36],
       [ 4, 42, 17, 40]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [108]:
# Create two arrays of random integers between 0 & 10 of the same shape
c11=np.random.randint(10, size=(3,3))
c12=np.random.randint(10, size=(3,3))


In [109]:
# Compare the two arrays with '>'
c11>c12

array([[False,  True, False],
       [False,  True,  True],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [110]:
# Compare the two arrays with '>='
c11>=c12

array([[False,  True, False],
       [False,  True,  True],
       [ True, False,  True]])

In [138]:
# Find which elements of the first array are greater than 7
c11>7

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [111]:
# Which parts of each array are equal? (try using '==')
c11==c12

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [112]:
# Sort one of the arrays you just created in ascending order
np.sort(c11)

array([[0, 1, 2],
       [4, 5, 9],
       [3, 6, 6]])

In [115]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1)

array([0, 1, 2], dtype=int32)

In [118]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(c11)

4

In [120]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(c11)

0

In [139]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(c11, axis=1)

array([1, 1, 0], dtype=int32)

In [140]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(c11, axis=0)

array([0, 0, 0], dtype=int32)

In [141]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.35674503,  0.5561218 ,  1.04386061,  0.52644816,  1.36388652],
       [ 2.53916272, -0.32449096, -0.20586672, -1.44004145,  1.19072726],
       [ 1.29939681, -0.86714616,  0.61764085,  1.2170708 ,  0.22628827]])

In [142]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.