In [1]:
import numpy as np

In [2]:
np.random.seed()
random_array=np.random.random((5,3))
random_array
##The only difference bwtewwn the random() 
# and random(7) is that the first allow the 
# program to give different values when you
# run it but the other gives a static value of random figures.

array([[0.98309791, 0.5047282 , 0.68618217],
       [0.74531977, 0.91104029, 0.62116199],
       [0.52794958, 0.30304626, 0.17727991],
       [0.58256516, 0.37531805, 0.04658635],
       [0.684497  , 0.17738367, 0.49901649]])

In [3]:
random_array.shape

(5, 3)

In [4]:
np.unique(random_array)

array([0.04658635, 0.17727991, 0.17738367, 0.30304626, 0.37531805,
       0.49901649, 0.5047282 , 0.52794958, 0.58256516, 0.62116199,
       0.684497  , 0.68618217, 0.74531977, 0.91104029, 0.98309791])

In [5]:
random_array[0,2]

0.6861821711366481

## how to reshape numpy array

In [6]:
np.random.randint(1,40, size=40)

array([20, 32, 23, 35, 28, 23, 18,  6, 19,  1, 39, 35,  7, 25, 17, 25, 27,
       22, 32, 24, 21,  8, 32,  3, 19, 15,  4, 25,  7,  8,  3, 34, 21, 10,
        4,  4, 15, 39, 23, 21])